services:
  maridb:
    image: mariadb:latest
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=todo
    ports:
      - "3306:3306"
    networks:
      - prep

  fastapi:
    build:
      context: .
      dockerfile: Dockerfile-dev
    ports:
      - "8050:8050"
    volumes:
      - .:/app
    networks:
      - prep
    command: uvicorn main:app --host 0.0.0.0 --port 8050 --reload
#    command: gunicorn main:app --workers 4 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8050 --timeout 180


networks:
  prep:
    driver: bridge
